apiVersion: apps/v1
kind: Deployment
metadata:
    name: discord-server-deployment
    labels:
        app: discord-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: discord-server
    template:
        metadata:
            labels:
                app: discord-server
        spec:
            containers:
                - image: discord.azurecr.io/discord-server:v0.0.1
                  name: discord-server
                  ports:
                      - containerPort: 3000
            imagePullSecrets:
                - name: azure-acr
---
apiVersion: v1
kind: Service
metadata:
    name: discord-server-service
spec:
    type: LoadBalancer
    selector:
        app: discord-server
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
