apiVersion: v1
kind: Service
metadata:
    name: discord-server-service
spec:
    type: NodePort
    selector:
        app: discord-server
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 31000
